version: 2.1

jobs:
  test:
    resource_class: medium+
    docker:
      - image: node:20
        environment:
          TZ: "Europe/Stockholm"
    steps:
      - checkout
      - run:
          name: Install PNPM
          command: yarn global add pnpm@8.15.8
      - run:
          name: Install dependencies
          command: pnpm install --frozen-lockfile
      - run:
          name: Run Tests
          command: pnpm test

workflows:
  sample:
    jobs:
      - test
